import Header from "@/components/header/Header";
import "./globals.css";
import { Suspense } from "react";

export const metadata = {
  title: "nextWatch",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Suspense>
          <Header />
          {children}
        </Suspense>
      </body>
    </html>
  );
}
